defmodule NFTScanClient.Collection do
  @moduledoc """
  Represents a collection from the NFTScan API.
  """

  @type t :: %__MODULE__{
    contract_address: String.t(),
    name: String.t(),
    symbol: String.t(),
    description: String.t() | nil,
    website: String.t() | nil,
    email: String.t() | nil,
    twitter: String.t() | nil,
    discord: String.t() | nil,
    telegram: String.t() | nil,
    github: String.t() | nil,
    instagram: String.t() | nil,
    medium: String.t() | nil,
    logo_url: String.t() | nil,
    banner_url: String.t() | nil,
    featured_url: String.t() | nil,
    large_image_url: String.t() | nil,
    attributes: list(map()),
    erc_type: String.t(),
    deploy_block_number: integer(),
    owner: String.t(),
    verified: boolean(),
    opensea_verified: boolean(),
    is_spam: boolean(),
    royalty: integer(),
    items_total: integer(),
    amounts_total: integer(),
    owners_total: integer(),
    opensea_floor_price: float() | nil,
    opensea_slug: String.t() | nil,
    floor_price: float() | nil,
    collections_with_same_name: list(String.t()),
    price_symbol: String.t()
  }

  defstruct [
    :contract_address,
    :name,
    :symbol,
    :description,
    :website,
    :email,
    :twitter,
    :discord,
    :telegram,
    :github,
    :instagram,
    :medium,
    :logo_url,
    :banner_url,
    :featured_url,
    :large_image_url,
    :attributes,
    :erc_type,
    :deploy_block_number,
    :owner,
    :verified,
    :opensea_verified,
    :is_spam,
    :royalty,
    :items_total,
    :amounts_total,
    :owners_total,
    :opensea_floor_price,
    :opensea_slug,
    :floor_price,
    :collections_with_same_name,
    :price_symbol
  ]

end
